### PR TITLE
Completed brochure

### PR DESCRIPTION
**Pull request by chrisahn1**
image

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
@chrisahn1 Please center the form on the page, as in the example screenshot:

---



---

**Comment by chrisahn1** [comment]
image

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Better. The form itself still needs some adjustments to look more like the example screenshot:

- The form shouldn't have a border.
- The placeholders need more spacing around them.
- The dropdown needs a light grey background.
- I can't tell for sure from the screenshot, but the whole thing looks much smaller than the example overall.

---

image

---

image

**Comment by chrisahn1** [comment]
image

**Review by TimelikeClosure — APPROVED** [review]
Almost. The inputs could be slightly width (see the size of the `<select>` vs its `<label>`), and the heading & submit button could be redder:

---

image

---

image

**Pull request merged**
